config/routes.rb
Rails.application.routes.draw do

  resources :groups
  resources :travels
  root 'users#profile'

  # get 'users/profile'

  devise_for :users

  get 'external', to: 'travels#external_travel'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_one_attached :icon

  belongs_to :user

  has_many :travel_groups, dependent: :destroy
  has_many :travels, through: :travel_groups

  scope :alphabetically, -> { order('name') }

  validates :name, presence: true, length: { in: 4..40 }
end

app/models/travel.rb
class Travel < ApplicationRecord
  belongs_to :user

  has_many :travel_groups, dependent: :destroy
  has_many :groups, through: :travel_groups

  validates :purpose, presence: true, length: { in: 4..40 }
  validates :source, presence: true, length: { in: 2..20 }
  validates :destination, presence: true, length: { in: 2..20 }
  validates :distance, presence: true

  scope :recent_first, -> { order('created_at DESC') }
end

app/models/travel_group.rb
class TravelGroup < ApplicationRecord
  belongs_to :travel
  belongs_to :group
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :travels
  has_many :groups

  has_one_attached :profile_pic

  validates :employee_id, presence: true, uniqueness: { case_sensitive: false }, length: { is: 5 }
  validates :name, presence: true, length: { in: 2..40 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:employee_id, :name, :email, :password) }

    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:employee_id, :name, :email, :password,
               :current_password, :profile_pic)
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]

  def index
    @groups = Group.includes(:user, :icon_attachment).alphabetically
  end

  def show
    @group_travels = @group.travels.includes(:user)
    @distance = @group_travels.pluck(:distance).sum
  end

  def new
    @group = Group.new
  end

  def edit; end

  def create
    @group = current_user.groups.build(group_params)

    if @group.save
      redirect_to group_path(@group), notice: 'Group was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @group.update(group_params)
      redirect_to group_path(@group), notice: 'Group was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @group.destroy
    redirect_to groups_url, notice: 'Group was successfully destroyed.'
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name, :user_id, :icon)
  end
end

app/controllers/travels_controller.rb
class TravelsController < ApplicationController
  before_action :set_travel, only: %i[show edit update destroy]

  def index
    @travels = my_travels
    @total_distance = current_user.travels.pluck(:distance).sum
  end

  def show; end

  def new
    @travel = Travel.new
  end

  def edit; end

  def create
    @travel = current_user.travels.build(travel_params)

    if @travel.save
      @travel.travel_groups.create(show_group_id)
      redirect_to travels_path, notice: 'Travel was successfully created.'
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def update
    if @travel.update(travel_params)

      if show_group_id[:group_id]
        if @travel.groups.empty?
          @travel.travel_groups.create(show_group_id)
        else
          @travel.travel_groups.update(show_group_id)
        end
      end

      redirect_to @travel, notice: 'Travel was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @travel.destroy
    redirect_to travels_path, notice: 'Travel was successfully destroyed'
  end

  def external_travel
    @external = my_travels.left_joins(:travel_groups).where('group_id IS NULL')
    @total_distance = @external.sum(:distance)
  end

  private

  def set_travel
    @travel = Travel.find(params[:id])
  end

  def travel_params
    params.require(:travel).permit(:purpose, :source, :destination, :distance, :user_id, group_ids: [])
  end

  def show_group_id
    params.require(:travel).permit(:group_id)
  end

  def my_travels
    current_user.travels.includes(:groups).recent_first
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def profile; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_messages_for(object)
    render(partial: 'devise/shared/error_messages', locals: { resource: object })
  end

  def login_logout
    if user_signed_in?
      link_to 'Sign out', destroy_user_session_path, method: :delete
    else
      link_to 'Login', new_user_session_path
    end
  end

  def home_signup
    if user_signed_in?
      link_to current_user.name.upcase, root_path
    else
      link_to 'Sign Up', new_user_registration_path
    end
  end

  def message(type, color)
    "<div class='#{type} chip #{color} lighten-4'>#{type}</div>".html_safe if type.present?
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  def group_icon(group)
    if group.icon.attached?
      image_tag group.icon, class: 'travel_item_icon'
    else
      image_tag 'travel_icon.jpg', class: 'travel_item_icon'
    end
  end

  def edit_group_link(group)
    return unless group.user_id == current_user.id

    link_to '<i class="small material-icons teal-text darken-4">mode_edit</i>'.html_safe, edit_group_path(group)
  end

  def delete_group_link(group)
    return unless group.user_id == current_user.id

    link_to '<i class="small material-icons deep-orange-text accent-3">delete</i>'.html_safe, group,
            method: :delete, data: { confirm: 'Are you sure?' }
  end

  def edit_travel_link(travel)
    return unless travel.user_id == current_user.id

    link_to '<i class="small material-icons teal-text darken-4">mode_edit</i>'.html_safe, edit_travel_path(travel)
  end

  def delete_travel_link(travel)
    return unless travel.user_id == current_user.id

    link_to '<i class="small material-icons deep-orange-text accent-3">delete</i>'.html_safe, travel,
            method: :delete, data: { confirm: 'Are you sure?' }
  end
end

app/helpers/travels_helper.rb
module TravelsHelper
  def travel_icon(travel)
    if travel.groups.first.nil?
      image_tag 'travel_icon.jpg', class: 'travel_item_icon'
    elsif !travel.groups.first.icon.attached?
      image_tag 'travel_icon.jpg', class: 'travel_item_icon'
    else
      image_tag travel.groups.first.icon, class: 'travel_item_icon'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def profile_avatar
    if current_user.profile_pic.attached?
      image_tag current_user.profile_pic, class: 'circle responsive-img profile_img'
    else
      image_tag 'blank_profile.png', class: 'circle responsive-img profile_img'
    end
  end
end

app/views/groups/_form.html.erb
<div class="col s12">
  <div class="card horizontal left-align">
    <div class="card-stacked">
      <div class="card-content">

        <%= form_with(model: group) do |form| %>

          <%= error_messages_for(group) %>

          <%= form.text_field :name, placeholder: 'Name' %>
          <%= form.file_field :icon %>

          <br/>
          <br/>
          <div class="btn waves-effect waves-light center">
            <%= form.submit %>
          </div>
        <% end %>
      </div>
      <div class="card-action">
        <%= link_to '<i class="small material-icons green-text darken-4">arrow_back</i>'.html_safe, groups_path %>
      </div>
    </div>
  </div>
</div>

app/views/groups/_group.html.erb
<ul class="collection">
  <li class="collection-item avatar">
    <div class="row travel_tile">
      <div class="col s2">
        <%=  link_to group_icon(group), group  %>
      </div>
      <div class="col s10">
        <span class="title pink-text accent-4">
          <%=  link_to group.name, group, class: 'pink-text'  %>
        </span>
        <div class="left-align">
          <p><span class="teal-text">Created By: </span> <%=  group.user.name  %></p>
          <p><span class="teal-text">Author Employee Id: </span> <%=  group.user.employee_id.upcase  %> </p>
          <p><span class="teal-text">Created On: </span> <%=  group.created_at.to_s(:long_ordinal)  %></p>
        </div>
      </div>
    </div>

    <h3 class="secondary-content">

    </h3>

    <div>
      <%= link_to '<i class="small material-icons indigo-text darken-4">visibility</i>'.html_safe, group %>
      <% if group.user_id == current_user.id %>
        <%= edit_group_link(group) %>
        <%= delete_group_link(group) %>
      <%  end  %>
    </div>
  </li>
</ul>

app/views/groups/_group_travel.html.erb
<ul class="collection">
  <li class="collection-item avatar">
    <div class="row travel_tile">
      <div class="col s2">
        <%= travel_icon(gt) %>
      </div>
      <div class="col s10">
          <span class="title pink-text accent-4">
            <%= gt.user.name %>
            <span> | </span>
            <%= gt.user.employee_id.upcase %>
          </span>
        <div class="left-align">
          <p><span class="teal-text">Purpose:</span> <%= gt.purpose %></p>
          <p><span class="teal-text">Source:</span> <%= gt.source %> </p>
          <p><span class="teal-text">Destination:</span> <%= gt.destination %></p>
          <p><span class="teal-text">Date:</span> <%= gt.created_at.to_s(:long_ordinal) %></p>
        </div>
      </div>
    </div>

    <h3 class="secondary-content">
      <%= gt.distance %>
      <span class="km">km</span>
    </h3>

    <div>
      <%= link_to '<i class="small material-icons indigo-text darken-4">visibility</i>'.html_safe, gt %>
      <%= edit_travel_link(gt) %>
      <%= delete_travel_link(gt) %>
    </div>
  </li>
</ul>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

app/views/groups/index.html.erb
<h1>All Groups</h1>

<div class="fixed-action-btn">
    <span class="btn-floating pulse btn-large red">
      <%= link_to '<i class="large material-icons">add</i>'.html_safe, new_group_path %>
    </span>
</div>

<%= render @groups %>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form', group: @group %>

app/views/groups/show.html.erb
<div class="card blue lighten-5">
  <div class="card-content teal-text darken-4">
    <%= group_icon(@group) %>
    <span class="card-title pink-text accent-1"><%= @group.name %></span>
    <p class="travel_show_text"><span class="brown-text darken-4">Created By: </span> <%= @group.user.name %></p>
    <p class="travel_show_text"><span class="brown-text darken-4">Author Employee Id: </span> <%= @group.user.employee_id %> </p>
    <p class="travel_show_text"><span class="brown-text darken-4">Created On: </span> <%= @group.created_at.to_s(:long_ordinal) %></p>
  </div>
  <div class="card-action right-align">
    <%= link_to '<i class="small material-icons green-text darken-4">arrow_back</i>'.html_safe, groups_path %>
    <%= edit_group_link(@group) %>
    <%= delete_group_link(@group) %>
  </div>
</div>


<div class="col s12 m7">
  <div class="card horizontal">
    <div class="card-stacked">
      <div class="card-content row secondary-content pink-text accent-4">
        <h3 class="col s8 left-align">Total Distance Travelled: </h3>
        <h3 class="col s4 right-align">
          <%= @distance %>
          <span class="km"> km</span>
        </h3>
      </div>
    </div>
  </div>
</div>

<%= render @group_travels %>


<%# @group_travels.each do |gt| %>
<!--  <ul class="collection">-->
<!--    <li class="collection-item avatar">-->
<!--      <div class="row travel_tile">-->
<!--        <div class="col s2">-->
          <%#= travel_icon(gt) %>
<!--        </div>-->
<!--        <div class="col s10">-->
<!--          <span class="title pink-text accent-4">-->
            <%#= gt.user.name %>
<!--            <span> | </span>-->
            <%#= gt.user.employee_id.upcase %>
<!--          </span>-->
<!--          <div class="left-align">-->
<!--            <p><span class="teal-text">Purpose:</span> <%#= gt.purpose %></p>-->
<!--            <p><span class="teal-text">Source:</span> <%#= gt.source %> </p>-->
<!--            <p><span class="teal-text">Destination:</span> <%#= gt.destination %></p>-->
<!--            <p><span class="teal-text">Date:</span> <%#= gt.created_at.to_s(:long_ordinal) %></p>-->
<!--          </div>-->
<!--        </div>-->
<!--      </div>-->

<!--      <h3 class="secondary-content">-->
        <%#= gt.distance %>
<!--        <span class="km">km</span>-->
<!--      </h3>-->

<!--      <div>-->
        <%#= link_to '<i class="small material-icons indigo-text darken-4">visibility</i>'.html_safe, gt %>
        <%#= edit_travel_link(gt) %>
        <%#= delete_travel_link(gt) %>
<!--      </div>-->
<!--    </li>-->
<!--  </ul>-->
<%# end %>

app/views/layouts/_footer.html.erb
<footer class="page-footer light-blue darken-3">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text brand-logo">Itinerant</h5>
        <p class="grey-text text-lighten-4">
          An app to Log your all travels records.
        </p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5>
          <%= link_to 'Home', root_path, class: 'white-text' %>
        </h5>
        <ul>
          <li><%= link_to 'All my Travel Logs', travels_path, class: 'grey-text text-lighten-3' %></li>
          <li><%= link_to 'All my External Travel Logs', external_path, class: 'grey-text text-lighten-3' %></li>
          <li><%= link_to 'All Groups', groups_path, class: 'grey-text text-lighten-3' %></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
      © 2021 Amit Kumar
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav>
  <div class="nav-wrapper light-blue darken-3">
    <%= link_to 'Itinerant', root_path , class: 'brand-logo'%>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li><%= login_logout %></li>
      <li><%= home_signup %></li>
    </ul>
  </div>
</nav>

app/views/layouts/_messages.html.erb
<%= message notice, 'green' %>

<%= message alert, 'red' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TravelLog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>

  </head>

  <body>

    <%= render 'layouts/header' %>

    <div class="container center-align">
      <br/>
      <br/>
      <div class="left-align">
        <%= render 'layouts/messages' %>
      </div>

      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/travels/_distance_sum.html.erb
<div class="col s12 m7">
  <div class="card horizontal">
    <div class="card-stacked">
      <div class="card-content row secondary-content pink-text accent-4">
        <h3 class="col s8 left-align">Total Distance Travelled: </h3>
        <h3 class="col s4 right-align">
          <%= distance %>
          <span class="km"> km</span>
        </h3>
      </div>
    </div>
  </div>
</div>

app/views/travels/_form.html.erb
<div class="col s12">
  <div class="card horizontal left-align">
    <div class="card-stacked">
      <div class="card-content">

        <%= form_with(model: travel) do |form| %>

          <%= error_messages_for(travel) %>

          <%= form.text_field :purpose, placeholder: 'Purpose' %>
          <%= form.text_field :source, placeholder: 'Source' %>
          <%= form.text_field :destination, placeholder: 'Destination' %>
          <%= form.number_field :distance, placeholder: 'Distance (in km)' %>

          <%= form.collection_check_boxes( :group_ids, Group.all, :id, :name ) %>

          <br/>
          <br/>
          <div class="btn waves-effect waves-light center">
            <%= form.submit %>
          </div>
        <% end %>
      </div>
      <div class="card-action">
        <%= link_to '<i class="small material-icons green-text darken-4">arrow_back</i>'.html_safe, travels_path %>
      </div>
    </div>
  </div>
</div>

app/views/travels/_my_travels.html.erb
<div class="fixed-action-btn">
    <span class="btn-floating pulse btn-large red">
      <%= link_to '<i class="large material-icons">add</i>'.html_safe, new_travel_path %>
    </span>
</div>

<%= render my_travels %>

app/views/travels/_travel.html.erb
<ul class="collection">
  <li class="collection-item avatar">
    <div class="row travel_tile">
      <div class="col s2">
        <%= travel_icon(travel) %>
      </div>
      <div class="col s10">
          <span class="title pink-text accent-4">
            <%= travel.user.name %>
            <span> | </span>
            <%= travel.user.employee_id.upcase %>
          </span>
        <div class="left-align">
          <p><span class="teal-text">Purpose:</span> <%= travel.purpose %></p>
          <p><span class="teal-text">Source:</span> <%= travel.source %> </p>
          <p><span class="teal-text">Destination:</span> <%= travel.destination %></p>
          <p><span class="teal-text">Date:</span> <%= travel.created_at.to_s(:long_ordinal) %></p>
        </div>
      </div>
    </div>

    <h3 class="secondary-content">
      <%= travel.distance %>
      <span class="km">km</span>
    </h3>

    <div>
      <%= link_to '<i class="small material-icons indigo-text darken-4">visibility</i>'.html_safe, travel %>
      <%= link_to '<i class="small material-icons teal-text darken-4">mode_edit</i>'.html_safe, edit_travel_path(travel) %>
      <%= link_to '<i class="small material-icons deep-orange-text accent-3">delete</i>'.html_safe, travel, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  </li>
</ul>

app/views/travels/edit.html.erb
<h1>Editing Travel</h1>

<%= render 'form', travel: @travel %>

app/views/travels/external_travel.html.erb
<%= render 'distance_sum', distance: @total_distance %>

<%= render 'my_travels', my_travels: @external %>

app/views/travels/index.html.erb
<%= render 'distance_sum', distance: @total_distance %>

<%= render 'my_travels', my_travels: @travels %>

app/views/travels/new.html.erb
<h1>Create New Travel Log</h1>

<%= render 'form', travel: @travel %>

app/views/travels/show.html.erb
<div class="card blue lighten-5">
  <div class="card-content teal-text darken-4">
    <%= travel_icon(@travel) %>
    <span class="card-title pink-text accent-1"><%= @travel.purpose %></span>
    <p class="travel_show_text"><span class="brown-text darken-4">From:</span> <%= @travel.source %></p>
    <p class="travel_show_text"><span class="brown-text darken-4">To:</span> <%= @travel.destination %></p>
    <p class="travel_show_text"><span class="brown-text darken-4">Distance Travelled:</span> <%= @travel.distance %><span>km</span></p>
    <p class="travel_show_text"><span class="brown-text darken-4">Date:</span> <%= @travel.created_at.to_s(:long_ordinal) %></p>
  </div>
  <div class="card-action right-align">
    <%= link_to '<i class="small material-icons green-text darken-4">arrow_back</i>'.html_safe, external_path %>
    <%= link_to '<i class="small material-icons">mode_edit</i>'.html_safe, edit_travel_path(@travel) %>
    <%= link_to '<i class="small material-icons red-text accent-3">delete</i>'.html_safe, @travel, method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
</div>

app/views/users/index.html.erb
<h1>Profile Page</h1>

<br/>
<%= current_user.name %><br/>
<%= current_user.employee_id %>


<br/>
<br/>

<%= link_to 'All my Travel-log', travels_path %><br/>
<%= link_to 'All my External Travel-log', external_path %><br/>
<%= link_to 'All groups', groups_path %>

app/views/users/profile.html.erb
<div class="row">
  <div class="col s12">
    <div class="card light-blue darken-1">
      <div class="card-content white-text">

        <%= profile_avatar %>

        <span class="btn-floating btn-large amber lighten-1">
          <%= link_to '<i class="large material-icons red-text">mode_edit</i>'.html_safe, edit_user_registration_path %>
        </span>

        <div class="profile_info">
          <p class="profile_info_name"><%= current_user.name %></p>
          <p><%= current_user.employee_id.upcase %></p>
          <p><%= current_user.email %></p>
        </div>
      </div>

      <div class="left-align profile_links">
          <p>
            <i class="material-icons white-text profile_icon">airplanemode_active</i>
            <%= link_to 'All my Travel-logs', travels_path, class: 'profile_link' %>
          </p>
          <p>
            <i class="material-icons white-text profile_icon">airplanemode_inactive</i>
            <%= link_to 'All my External Travel-logs', external_path, class: 'profile_link' %>
          </p>
          <p>
            <i class="material-icons white-text profile_icon">people</i>
            <%= link_to 'All groups', groups_path, class: 'profile_link' %>
          </p>
      </div>

    </div>
  </div>
</div>